Added Triangle shape
ashutosh1919/react-awesome-shapes pull request #36
Opened 2022-02-26 02:39 UTC by judy-n

2022-02-26 04:07 UTC, ashutosh1919 commented
@judy-n Thank you so much for raising PR. Let this PR stay open for 3-4 days. Since we have released the project yesterday, we want to stabilize the traffic as of now. I will start reviewing PRs starting from Monday (1st March) 💯

2022-03-01 02:24 UTC, ashutosh1919 requested changes
@judy-n , Thanks for contribution.

Below are some of the issues that you can fix before we can merge. Other than below issues, there is one more thing that you need to add.

In [Usage section of readme](https://github.com/ashutosh1919/react-awesome-shapes#usage), you need to add new shape name and you need to link it with the `triangle.tsx`.

2022-03-01 02:24 UTC, ashutosh1919 commented on src/components/shapesdemos.tsx
> +    color="linear-gradient(135deg, #f9a8d4, #eab309)"
```suggestion
    color="linear-gradient(135deg, #fde047, #eab308)"
```

We are following [tailwind colors](https://tailwindcss.com/docs/customizing-colors) so it is good to stay consistent with the gradient theme which we have used in other components.

2022-03-01 03:35 UTC, judy-n commented
@ashutosh1919 I just committed the changes 👍

2022-03-01 03:54 UTC, merged

2022-03-01 03:55 UTC, ashutosh1919 commented
@all-contributors please add @judy-n for code

2022-03-01 04:15 UTC, ashutosh1919 commented
Fixed #30