created hexagon shape
ashutosh1919/react-awesome-shapes pull request #37
Opened 2022-02-26 03:15 UTC by JLambertazzo

2022-02-26 04:07 UTC, ashutosh1919 commented
@JLambertazzo Thank you so much for raising PR. Let this PR stay open for 3-4 days. Since we have released the project yesterday, we want to stabilize the traffic as of now. I will start reviewing PRs starting from Monday (1st March) 💯

2022-03-01 02:17 UTC, ashutosh1919 requested changes
@JLambertazzo , Thanks for contribution.

Below are some of the issues that you can fix before we can merge. Other than below issues, there is one more thing that you need to add.

In [Usage section of readme](https://github.com/ashutosh1919/react-awesome-shapes#usage), you need to add new shape name and you need to link it with the `hexagon.tsx`.

2022-03-01 02:17 UTC, ashutosh1919 commented on src/components/shapesdemos.tsx
> +    color="linear-gradient(135deg, #7b2cbf, #3c096c)"
```suggestion
    color="linear-gradient(135deg, #c4b5fd, #8b5cf6)"
```

We are following [tailwind colors](https://tailwindcss.com/docs/customizing-colors) so it is good to stay consistent with the gradient theme which we have used in other components.

2022-03-01 02:17 UTC, ashutosh1919 commented on src/lib/shapes/hexagon.tsx
> +  size,
```suggestion
```

`size` is not used anywhere in the shape so can you please remove it?

2022-03-01 02:17 UTC, ashutosh1919 commented on src/lib/shapes/hexagon.tsx
> +  size: string | string[];
```suggestion
```

Please remove `size` from here as well.

2022-03-01 03:35 UTC, JLambertazzo commented
Hey sounds good! Changes have been made 👍

2022-03-01 04:03 UTC, ashutosh1919 requested changes

2022-03-01 04:03 UTC, ashutosh1919 commented on src/components/shapesdemos.tsx
> +
```suggestion
```

2022-03-01 04:05 UTC, merged

2022-03-01 04:06 UTC, ashutosh1919 commented
@all-contributors please add @JLambertazzo for code

2022-03-01 04:14 UTC, ashutosh1919 commented
Fixed #30