Created Polygon Shape
ashutosh1919/react-awesome-shapes pull request #46
Opened 2022-03-03 06:14 UTC by JLambertazzo

Created polygon shape with clip-path depending on sides prop (sides in [3,10])

2022-03-03 14:48 UTC, Sachin-chaurasiya requested changes
One minor change, Otherwise LGTM!

2022-03-04 04:30 UTC, Sachin-chaurasiya commented on src/lib/shapes/polygon.tsx
> +import { clipPathMap } from './polygonclippath.tsx'
The filename should be `polygonclippath.ts`.

2022-03-04 14:09 UTC, JLambertazzo commented
Made requested changes also forgot to reference this is Issue #42

2022-03-04 14:54 UTC, Sachin-chaurasiya approved these changes
LGTM! , @ashutosh1919 Please review once.

2022-03-04 23:23 UTC, ashutosh1919 approved these changes
LGTM. Thanks for contribution @JLambertazzo .

2022-03-04 23:23 UTC, merged