Fix: issue-45 diamond to square
ashutosh1919/react-awesome-shapes pull request #70
Opened 2022-03-12 18:17 UTC by ShaileshParmar11

I work on fixing issue #45 which converts diamond shape in to square shape on animation.
Closes #45 

Working example:- Please look right top corner for diamond shape

https://user-images.githubusercontent.com/71748675/158029836-3b14c96e-202a-4159-9eba-70326f7e4a66.mov

@Sachin-chaurasiya @Spyware007

2022-03-12 18:38 UTC, ashutosh1919 requested changes
Please apply `upKeyframe` in `shapes.tsx` for diamond. It will help see whether the problem is fixed or not.

2022-03-13 05:16 UTC, ShaileshParmar11 commented
> Please apply `upKeyframe` in `shapes.tsx` for diamond. It will help see whether the problem is fixed or not.

Hi @ashutosh1919, I have added `upKeyFrame` kindly check and let me know if anything more need to address for this issue.

2022-03-13 05:26 UTC, ashutosh1919 requested changes

2022-03-13 05:26 UTC, ashutosh1919 commented on src/components/shapes.tsx
> +        size="50px"
Why increase in size? please keep the size same.

2022-03-13 05:38 UTC, merged

2022-03-13 05:39 UTC, ashutosh1919 commented
@all-contributors please add @ShaileshParmar11 for code